/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
static yyconst short int yy_accept[196] =
    {   0,
        0,    0,    0,    0,    0,    0,   66,   64,   53,   55,
       63,   64,    2,   64,   64,   52,   56,   60,   57,   59,
       28,   64,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   65,   47,   48,   65,   65,
       50,   53,   58,    0,   40,   39,    0,    2,    1,   35,
       36,   30,    0,    0,    3,    0,   52,    0,   62,   61,
       28,   54,   28,   28,   28,   28,   28,   28,   28,   15,
       28,   28,   28,   28,   12,   25,   28,   19,   28,   28,
       28,   28,   28,    0,   47,   48,    0,   46,   44,   46,
        0,   50,   41,   41,   41,   29,   30,    0,    0,    0,

       52,    0,    0,   28,   20,   28,   28,   28,   28,   28,
       28,   11,   28,   28,   28,   28,   18,   28,   28,   28,
       28,   28,   28,   44,   45,   42,   43,    0,   37,    0,
        0,   32,    0,    0,   52,    0,   49,    0,    5,    4,
       28,   28,   24,   28,   13,    9,   28,   28,   28,   28,
       28,    7,    0,   28,   28,   44,   45,   42,   43,    0,
        0,   31,    0,    0,   10,   16,   28,   28,   28,   21,
        6,   28,    0,    0,   27,   22,   14,    0,   38,    0,
       34,    0,    0,   28,    8,   23,   26,   33,   51,    0,
       28,   51,   17,   51,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    9,    1,
        1,    1,    1,    1,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   13,   13,   14,   15,   16,
       17,   18,    8,    1,   19,   19,   19,   19,   19,   19,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   20,   20,
        1,   22,    1,    1,   20,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   20,   32,   33,   20,   34,
       35,   36,   20,   37,   38,   39,   40,   20,   41,   42,
       20,   20,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        5,    6,    6,    7,    1,    1,    1,    1,    8,    9,
        9,    1,    8,    8,    8,    8,    8,    8,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    3,    7
    } ;

static yyconst short int yy_base[220] =
    {   0,
        0,    0,   42,   43,  440,  439,  441,  444,  438,  444,
      422,   46,  435,   44,  428,   41,  444,   42,  444,  419,
        0,  432,   35,   34,   32,  399,   39,  406,   42,  397,
      394,  393,  402,   36,  398,   74,   75,  444,   62,  424,
      444,  424,  444,   79,   83,  444,   73,  422,  444,  444,
       77,  414,   79,  414,  444,   86,   95,  412,  444,  444,
        0,  444,  396,  394,  380,  389,  390,  378,  381,    0,
      376,  387,   64,  373,    0,  375,  371,    0,  371,  354,
       75,  341,  338,  107,  108,  444,   81,  444,  339,    0,
      345,  444,  444,  332,    0,  333,  332,  104,   89,  108,

      113,  328,  148,  295,    0,  293,  274,  269,  250,  236,
      247,    0,  195,  206,  197,  191,    0,  196,  189,  202,
      225,  198,  192,  212,    0,  211,    0,  124,  444,  114,
      129,  212,  123,  148,  132,  218,  444,  192,    0,    0,
      186,  187,    0,  187,    0,    0,  192,  180,  176,  174,
      175,    0,  165,  172,  178,  444,  444,  444,  444,  160,
      159,  444,  160,  191,    0,    0,  156,  150,  149,    0,
        0,  153,  183,  172,  444,    0,    0,  125,  103,   96,
      132,  165,  168,   91,    0,    0,    0,   83,  170,  111,
       35,  172,    0,  444,  444,  236,  245,  254,  263,  270,

      279,  285,  294,  303,  312,  321,  327,  331,  337,  341,
      344,  349,  358,  362,  365,  373,  382,  391,  400
    } ;

static yyconst short int yy_def[220] =
    {   0,
      195,    1,  196,  196,  197,  197,  195,  195,  195,  195,
      195,  198,  199,  200,  201,  195,  195,  195,  195,  195,
      202,  195,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  203,  203,  195,  204,  205,
      195,  195,  195,  198,  198,  195,  206,  199,  195,  195,
      195,  207,  208,  201,  195,  195,  195,  209,  195,  195,
      202,  195,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  203,  203,  195,  204,  195,  195,  210,
      205,  195,  195,  195,  211,  207,  207,  195,  212,  195,

      195,  209,  213,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  195,  214,  195,  215,  195,  195,  212,
      195,  195,  195,  195,  195,  216,  195,  213,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  217,  202,  202,  195,  195,  195,  195,  218,
      219,  195,  195,  195,  202,  202,  202,  202,  202,  202,
      202,  202,  217,  217,  195,  202,  202,  218,  218,  219,
      219,  195,  195,  202,  202,  202,  202,  219,  195,  195,
      202,  195,  202,  195,    0,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195
    } ;

static yyconst short int yy_nxt[489] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,    8,   15,    8,
        8,   16,   16,    8,   17,   18,   19,   20,   21,   21,
       21,   22,   23,   24,   25,   26,   27,   21,   28,   21,
       29,   21,   21,   30,   31,   32,   33,   34,   21,   21,
       35,   21,    8,    8,   37,   37,   38,   38,   45,   50,
       46,   56,   57,   57,   68,   51,   51,   58,   59,   63,
       66,  193,   81,   39,   39,   82,   69,   47,   64,   75,
       67,   71,   72,   89,   65,   76,   85,   85,   86,   86,
       73,   45,   90,   46,   94,   45,   53,   46,   51,   51,
       98,   98,   89,   95,  113,   87,   87,  100,  100,  114,

       47,   90,  131,   90,   47,   56,  101,  101,  120,   85,
       85,   86,   86,  121,   95,   98,   98,  128,  133,  134,
      134,  182,   90,   56,  135,  135,  181,  131,   87,   87,
      191,  160,  132,  160,  163,  163,  161,  160,  161,  181,
      160,  188,  161,  135,  135,  161,  179,  129,  136,  136,
      137,  136,  136,  136,  136,  136,  136,  132,  133,  164,
      164,  136,  136,  136,  136,  136,  174,  175,  179,  136,
      182,  183,  183,  174,  175,  181,  189,  189,  182,  190,
      190,  192,  192,  194,  194,  175,  187,  186,  185,  184,
      136,  136,  136,  136,  137,  136,  136,  136,  136,  136,

      136,  133,  181,  179,  177,  136,  136,  136,  136,  136,
      176,  172,  171,  136,  170,  169,  168,  167,  166,  165,
      137,  162,  158,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  136,  136,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   52,  145,  144,   52,  143,   52,   52,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   61,   61,
       61,  142,   61,   61,   84,   84,   84,   84,   84,   84,

       84,   84,   84,   88,  141,   88,   88,   88,   88,   88,
       88,   88,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   93,  140,   93,   93,   93,   93,   93,   93,   93,
       97,   97,   97,  139,   97,   97,   99,  195,   99,   99,
      103,   96,   96,  126,  103,  103,  125,   92,  125,  127,
      124,  127,  130,  130,  130,  130,  130,  130,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  157,  123,  157,
      159,  122,  159,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  178,  119,  178,  178,  178,  178,  178,  178,  178,

      180,  118,  180,  180,  180,  180,  180,  180,  180,  117,
      116,  115,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  102,   55,   96,   49,   42,   92,   83,   80,   79,
       78,   77,   74,   70,   62,   60,   55,   49,   43,   42,
      195,   41,   41,    7,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195
    } ;

static yyconst short int yy_chk[489] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,   12,   14,
       12,   16,   16,   16,   25,   14,   14,   18,   18,   23,
       24,  191,   34,    3,    4,   34,   25,   12,   23,   29,
       24,   27,   27,   39,   23,   29,   36,   37,   36,   37,
       27,   44,   39,   44,   47,   45,   14,   45,   51,   51,
       53,   53,   87,   47,   73,   36,   37,   56,   56,   73,

       44,   87,   99,   39,   45,   57,   57,   57,   81,   84,
       85,   84,   85,   81,   47,   98,   98,   98,  100,  100,
      100,  190,   87,  101,  101,  101,  188,  130,   84,   85,
      184,  128,   99,  128,  133,  133,  131,  128,  131,  180,
      128,  181,  131,  135,  135,  131,  179,   98,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  130,  134,  134,
      134,  103,  103,  103,  103,  103,  153,  153,  178,  103,
      163,  163,  163,  174,  174,  181,  182,  182,  183,  183,
      183,  189,  189,  192,  192,  173,  172,  169,  168,  167,
      103,  103,  138,  138,  138,  138,  138,  138,  138,  138,

      138,  164,  161,  160,  155,  138,  138,  138,  138,  138,
      154,  151,  150,  138,  149,  148,  147,  144,  142,  141,
      136,  132,  126,  124,  123,  122,  121,  120,  119,  118,
      116,  115,  114,  113,  138,  138,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  200,  111,  110,  200,  109,  200,  200,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  202,  202,
      202,  108,  202,  202,  203,  203,  203,  203,  203,  203,

      203,  203,  203,  204,  107,  204,  204,  204,  204,  204,
      204,  204,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  206,  106,  206,  206,  206,  206,  206,  206,  206,
      207,  207,  207,  104,  207,  207,  208,  102,  208,  208,
      209,   97,   96,   94,  209,  209,  210,   91,  210,  211,
       89,  211,  212,  212,  212,  212,  212,  212,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  214,   83,  214,
      215,   82,  215,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  218,   80,  218,  218,  218,  218,  218,  218,  218,

      219,   79,  219,  219,  219,  219,  219,  219,  219,   77,
       76,   74,   72,   71,   69,   68,   67,   66,   65,   64,
       63,   58,   54,   52,   48,   42,   40,   35,   33,   32,
       31,   30,   28,   26,   22,   20,   15,   13,   11,    9,
        7,    6,    5,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "input.l"
#define INITIAL 0
#define STRING 1
#define HEREDOC 2

#line 3 "input.l"
/* This file is part of GNU Radius.
   Copyright (C) 2000,2001,2002,2003,2004,2005,
   2007,2008 Free Software Foundation, Inc.

   Written by Sergey Poznyakoff
 
   GNU Radius is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.
 
   GNU Radius is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
 
   You should have received a copy of the GNU General Public License
   along with GNU Radius; if not, write to the Free Software Foundation,
   Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */

#if defined(HAVE_CONFIG_H)        
# include <config.h>
#endif
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <netinet/in.h>
         
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <fcntl.h>
#include <time.h>
#include <ctype.h>
#include <unistd.h>
#include <signal.h>
#include <errno.h>
#include <sys/wait.h>

#include <common.h>
#include <radius/radius.h>	
#include <radtest.h>
#include "gram.h"

#if !HAVE_DECL_GETLINE
int getline (char **lineptr, size_t *n, FILE *stream);
#endif

int interactive;                   /* Are we in interactive mode? */
char prompt_str[] = "radtest> ";   /* Prompt string for interactive mode */
grad_locus_t source_locus;         /* Current location in the source file */
static struct obstack string_stk;  /* Keeps all string literals. Gets freed
				      after compilation and (eventual)
				      execution of the statement */

size_t string_start_line;          /* In STRING and HEREDOC mode keeps
				      the line where the string definition
				      has started */

/* Here document support */ 
static char *heredoc_delimiter;    /* End delimiter for here document */ 
static int strip_tabs;             /* Strip leading tab characters */
 

/* Input buffer */

/* The variables below are used only in interactive mode */ 
static char *input_line;           /* Input line */
static size_t input_length;        /* Size of input_line */
static size_t input_pos;           /* Current position in input_line */

/* Read from the input stream at most `bufsize' character into buffer `buf' */
static int
fill_input_buffer(char *buf, int bufsize)
{
	if (interactive) {
		int rest;
		
		if (!input_line || input_pos == input_length) {
			if (disable_readline) {
				static size_t input_size;
				
				printf("%s", prompt_str);
				fflush(stdout);
				
				if (getline(&input_line, &input_size,
					    yyin) < 0) {
					free (input_line);
					input_line = NULL;
					input_length = 0;
					return 0;
				}
				input_length = strlen(input_line);
				input_pos = 0;
			} else {
				free(input_line);
				input_line = grad_readline(prompt_str);
				if (!input_line)
					return 0;
				grad_add_history(input_line);
				input_length = strlen (input_line);
				input_line = realloc(input_line,
						     input_length+2);
				if (!input_line) {
					fprintf (stderr,
						 _("low core: aborting"));
					abort();
				}
				input_line[input_length++] = '\n';
				input_line[input_length] = 0;
				input_pos = 0;
			}
		}
		rest = input_length - input_pos;
		if (bufsize > rest)
			bufsize = rest;
		memcpy(buf, input_line + input_pos, bufsize);
		input_pos += bufsize;
		return bufsize;
	} else {
		return fread(buf, 1, bufsize, yyin);
	}
}
			
#ifdef FLEX_SCANNER
/* Input support for flex */
 
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
  result = fill_input_buffer(buf, max_size)

#else /* !FLEX_SCANNER */
/* Input processing for AT&T Lex. Untested. */

static int
xinput()
{
	char c;
	if (fill_input_buffer(&c, 1) <= 0)
		return EOF;
	return c;
}

static int
xunput(int c)
{
	if (input_pos == 0) 
		abort();
	return input_line[--input_pos] = c;
}
 
#undef unput
#define unput(c) xunput(c)
#undef input
#define input() xinput()

#endif /* FLEX_SCANNER */ 

static size_t string_len;
static int binary_string;

/* Forward declarations */
static void begin_str();
static void add_str(char *str, int  len);
static void add_chr(int c);
static char *end_str();
static void add_num(int skip, int base, char *text, int leng);

static int backspace(int c);

static int isemptystr(char *text);
static char *heredoc_strip_tabs(char *text);
static void heredoc_begin();

#line 718 "input.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 187 "input.l"

#line 871 "input.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 196 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 444 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 188 "input.l"
{ /* a comment */
        source_locus.line++;
        return EOL;
}       
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 192 "input.l"
/* end-of-file comment */;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 193 "input.l"
{
	add_str(yytext+1,yyleng-2);
        yylval.string = end_str();
        return NAME;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 198 "input.l"
return AUTH;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 199 "input.l"
return ACCT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 200 "input.l"
return PRINT;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 201 "input.l"
return SEND;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 202 "input.l"
return EXPECT;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 203 "input.l"
return EXIT;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 204 "input.l"
return T_BEGIN; 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 205 "input.l"
return T_END;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 206 "input.l"
return IF;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 207 "input.l"
{
	switch (peek_ctx()) {
	case ctx_if:
	          return ELSE;

	case ctx_iferr:
		pop_ctx();
		break;

	default:
		  parse_error(_("Misplaced 'else'"));
		  /* Skip the token */
	}
} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 221 "input.l"
{
	if (peek_ctx() == ctx_doerr) 
		pop_ctx();
	else
		return WHILE;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 227 "input.l"
return DO;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 228 "input.l"
return BREAK;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 229 "input.l"
return CONTINUE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 230 "input.l"
return NOT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 231 "input.l"
return OR;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 232 "input.l"
return AND;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 233 "input.l"
return INPUT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 234 "input.l"
return SHIFT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 235 "input.l"
return GETOPT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 236 "input.l"
return CASE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 237 "input.l"
return IN;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 238 "input.l"
return T_RETURN;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 239 "input.l"
{
	int i, argc;
	char **argv;
	char *p;
	
	grad_argcv_get(yytext, "", NULL, &argc, &argv);
	for (i = 0; i < argc; i++) 
		add_str(argv[i], strlen(argv[i])+1);

	add_chr(0);
	for (p = end_str(); *p; p += strlen(p) + 1)
		obstack_ptr_grow(&string_stk, p);
	p = NULL;
	obstack_ptr_grow(&string_stk, p);
	yylval.set.argc = argc;
	yylval.set.argv = obstack_finish(&string_stk);
	grad_argcv_free(argc, argv);
	if (yytext[yyleng-2] == '\\')
		yyless(yyleng-2);
	else
		yyless(yyleng-1);
	return SET;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 262 "input.l"
{
	int n = grad_request_name_to_code(yytext);
	if (n != 0) {
		yylval.number = n;
		return NUMBER;
	}
	add_str(yytext,yyleng);
        yylval.string = end_str();
        return NAME;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 272 "input.l"
{
	add_str(yytext+1,yyleng-2);
	yylval.deref.name = end_str();
	yylval.deref.repl = NULL;
	yyless(yyleng-1);
	return IDENT;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 279 "input.l"
{
	add_str(yytext+1,yyleng-1);
	yylval.deref.name = end_str();
	yylval.deref.repl = NULL;
	return IDENT;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 285 "input.l"
{
	add_str(yytext+2, yyleng-4);
        yylval.deref.name = end_str();
	yylval.deref.repl = NULL;
	yyless(yyleng-1);
        return IDENT;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 292 "input.l"
{
	add_str(yytext+2, yyleng-3);
        yylval.deref.name = end_str();
	yylval.deref.repl = NULL;
        return IDENT;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 298 "input.l"
{
	char *p;
	add_str(yytext+2, yyleng-4);
        yylval.deref.name = end_str();
	p = strchr(yylval.deref.name, ':');
	*p++ = 0;
	yylval.deref.repl = p;
	yyless(yyleng-1);
        return IDENT;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 308 "input.l"
{
	char *p;
	add_str(yytext+2, yyleng-3);
        yylval.deref.name = end_str();
	p = strchr(yylval.deref.name, ':');
	*p++ = 0;
	yylval.deref.repl = p;
        return IDENT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 317 "input.l"
return ARGCOUNT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 318 "input.l"
{
	yylval.parm.number = strtoul(yytext+1, NULL, 0);
	yylval.parm.repl = NULL;
	return PARM;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 323 "input.l"
{
	yylval.parm.number = strtoul(yytext+2, NULL, 0);
	yylval.parm.repl = NULL;
	return PARM;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 328 "input.l"
{
	char *p;
	yylval.parm.number = strtoul(yytext+2, &p, 0);
	p++;
	add_str(p, strlen(p)-1);
	yylval.parm.repl = end_str();
	return PARM;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 336 "input.l"
{
        begin_str();
        add_str(yytext+1, yyleng-2);
        yylval.string = end_str();
        return QUOTE;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 342 "input.l"
{
        BEGIN(STRING);
        begin_str();
	string_start_line = source_locus.line++;
        add_str(yytext+1, yyleng-1);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 348 "input.l"
{
        BEGIN(STRING);
        begin_str();
        string_start_line = source_locus.line;
        if (yytext[yyleng-1] == '\n')
                source_locus.line++;
        add_str(yytext+1, yyleng - 3);
        add_chr(backspace(yytext[yyleng-1]));
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 357 "input.l"
{
        BEGIN(STRING);
        begin_str();
        add_num(0, 8, yytext+1, yyleng-1);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 362 "input.l"
{
        BEGIN(STRING);
        begin_str();
        add_num(1, 16, yytext+1, yyleng-1);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 367 "input.l"
{
        add_num(0, 8, yytext, yyleng);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 370 "input.l"
{
        add_num(1, 16, yytext, yyleng);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 373 "input.l"
{
        if (yytext[yyleng-1] == '\n')
                source_locus.line++;
        add_str(yytext, yyleng - 2);
        add_chr(backspace(yytext[yyleng-1]));
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 379 "input.l"
{
        source_locus.line++;
        add_str(yytext, yyleng);
        add_chr(backspace(yytext[yyleng-1]));
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 384 "input.l"
{
        BEGIN(INITIAL);
        add_str(yytext, yyleng - 1);
        if (binary_string) {
            yylval.bstring.ptr = end_str();
            yylval.bstring.length = string_len;
            return BSTRING;
        } else {
            yylval.string = end_str();
            return QUOTE;
        }
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 396 "input.l"
{
	BEGIN(HEREDOC);
        begin_str();
	string_start_line = source_locus.line++;
	heredoc_begin();
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 402 "input.l"
{
	char *p = heredoc_strip_tabs (yytext);
	if (strncmp (p, heredoc_delimiter, strlen (heredoc_delimiter))
	    == 0
	    && isemptystr (p + strlen (heredoc_delimiter))) {
		grad_free (heredoc_delimiter);
		heredoc_delimiter = NULL;
		BEGIN(INITIAL);
		yylval.string = end_str();
		yyless(yyleng-1);
		return QUOTE;
	}
	add_str(p, strlen(p));
        source_locus.line++;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 417 "input.l"
{
        yylval.ipaddr = grad_ip_strtoip(yytext);
        return IPADDRESS;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 421 "input.l"
{
        yylval.number = strtol(yytext, NULL, 0);
        return NUMBER;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 425 "input.l"
;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 426 "input.l"
source_locus.line++;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 427 "input.l"
{ source_locus.line++; return EOL; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 428 "input.l"
return EOL;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 429 "input.l"
return EQ;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 430 "input.l"
return NE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 431 "input.l"
return GT;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 432 "input.l"
return LT;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 433 "input.l"
return GE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 434 "input.l"
return LE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 435 "input.l"
return NOT;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 436 "input.l"
return yytext[0];
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 438 "input.l"
ECHO;
	YY_BREAK
#line 1464 "input.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(HEREDOC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 196 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 196 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 195);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 438 "input.l"


int
yywrap()
{
	if (YYSTATE == STRING) 
		parse_error(_("Unexpected end of file in string started on line %lu"),
			    string_start_line);
	else if (YYSTATE == HEREDOC)
		parse_error(_("Unexpected end of file in multiline string started on line %lu"),
			    string_start_line);
		
	grad_write_history_file();
        return 1;
}

int
open_input(char *name)
{
        FILE *fp;

        obstack_init(&string_stk);
        if (name && strcmp(name, "-")) {
                source_locus.file = name;
                fp = fopen(name, "r");
                if (!fp) {
                        grad_log(GRAD_LOG_ERR|GRAD_LOG_PERROR,
                                 _("can't open input file `%s'"), name);
                        return 1;
                }
        } else {
                source_locus.file = "<teletype>";
                fp = stdin;
        }

	interactive = isatty(fileno(fp));
	grad_readline_init("radtest", interactive, radtest_command_completion);
	if (interactive) 
		grad_readline_set_input(fp);
	grad_read_history_file();

        source_locus.line = 1;
#ifdef FLEX_SCANNER
        yyrestart(fp);
#else
        yyin = fp;
#endif
        return 0;
}

void
close_input()
{
#ifdef FLEX_SCANNER     
        yy_delete_buffer(YY_CURRENT_BUFFER); 
#endif  
        fclose(yyin);
        yyin = NULL;
        obstack_free(&string_stk, NULL);
}


/* String processing functions */

/* Read string segment ending with a numeric escape (\0.. or \x),
   and append it to the current string object.
   Arguments:
     skip     Number of characters to skip when processing the escape:
              0 for octal escapes, 1 -- for hex ones.
     base     Conversion base for the escape.
     text     Start of the string segment.
     leng     Length of the string segment. */
void
add_num(int skip, int base, char *text, int leng)
{
        int n;

        n = 1;
        while (leng - n > 0 && text[leng - n] != '\\')
                n++;
        add_str(text, leng - n);
        n -= skip;
        add_chr(strtol(&text[leng - n + 1], NULL, base));
}

void
begin_str()
{
	string_len = 0;
	binary_string = 0;
}

/* Append simple string segment to the current string object */
void
add_str(char *str, int len)
{
        obstack_grow(&string_stk, str, len);
        string_len += len;
}

/* Append a single character */
void
add_chr(int c)
{
        obstack_1grow(&string_stk, c);
        string_len++;
	if (c == 0)
		binary_string++;
}

/* Finish the string being constructed. Return pointer to its beginning. */
char *
end_str()
{
	obstack_1grow(&string_stk, 0);
        return obstack_finish(&string_stk);
}

/* Translate a second part of a C escape */
int
backspace(int c)
{
        switch (c) {
        case '\\':
                return '\\';
        case 'a':
                return '\a';
        case 'b':
                return '\b';
        case 'f':
                return '\f';
        case 'n':
                return '\n';
        case 'r':
                return '\r';
        case 't':
                return '\t';
        case 'e':
                return '\033';
        }
        return c;
}

/* External interfaces to the above functions */
void
radtest_start_string(char *str)
{
	/* FIXME: Make sure no leading garbage appears */
	add_str(str, strlen(str));
}

void
radtest_add_string(char *str)
{
	add_str(str, strlen(str));
}

char *
radtest_end_string()
{
	return end_str();
}

/* Free all string literals */
void
radtest_free_strings()
{
	obstack_free(&string_stk, NULL);
	obstack_init(&string_stk);
}

/* This function is called when we have to remember all collected
   string literals (e.g. for a function definition).
   Current implementation simply re-initializes string stack. A
   (possibly) better approach:
   use some start_ptr and do obstack_free(&string_stk, start_ptr) in
   radtest_free_strings(). Then it should suffice to do

   obstack_1grow(&string_stk, 0);
   start_ptr = obstack_finish(&string_stk)

   here. */

void
radtest_fix_strings()
{
	obstack_init(&string_stk);
}


/* "Here document" support */

/* Return 1 if `text' is an empty string */
static int
isemptystr(char *text)
{
	for (; *text && isspace (*text); text++)
		;
	return *text == 0;
}

/* Strip initial tab characters from `text' */
static char *
heredoc_strip_tabs(char *text)
{
	if (strip_tabs)
		for (; *text == '\t'; text++)
			;
	return text;
}

/* Begin processing of a "here document" construct */
static void
heredoc_begin()
{
	char *p = yytext + 2; /* past the << marker */

	if (*p == '-') {
		strip_tabs = 1;
		p++;
	}
	else
		strip_tabs = 0;

	if (!isspace (*p)) {
		char *endp;
		int len;
      
		for (endp = p; *endp; endp++)
			if (isspace (*endp))
				break;

		len = endp - p;
		heredoc_delimiter = grad_emalloc(len + 1);
		memcpy(heredoc_delimiter, p, len);
		heredoc_delimiter[len] = 0;
	} else {
		heredoc_delimiter = grad_estrdup (".");
	}
}

/* End of input.l */
