@c This is part of the Radius manual.
@c Copyright (C) 1999-2025 Free Software Foundation, Inc.
@c Written by Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Invocation, Configuration Files, Operation, Top
@chapter How to Start the Daemon.
@cindex Radius daemon invocation
@cindex Invoking the radius daemon
@pindex radiusd

When started @command{radiusd} uses the configuration values from the following
sources (in order of increasing precedence):

@itemize @bullet
@item Compiled-in defaults
@item @file{raddb/config} file.
@item Command line arguments
@end itemize

Whenever a command line options has its equivalent in config file the
use of this equivalent should be preferred (@pxref{config file}).

The following command line options are accepted:

@table @option

@c ** -A option (radiusd)
@c ** --log-auth-detail (radiusd)
@item -A
@itemx --log-auth-detail
Enable detailed authentication logging. When this option is specified
each authentication request is logged to the file
@file{radacct/NASNAME/detail.auth}, where NASNAME is replaced by the
short name of the @NAS{} from @file{raddb/naslist}
@ref{Naming Conventions}.

Config file equivalent: @code{auth @{ detail yes; @};}.

@c ** -a option (radiusd)
@c ** --acct-directory (radiusd)
@item -a @var{dir}
@itemx --acct-directory=@var{dir}
Specify accounting directory.

Config file equivalent: @code{option @{ acct-dir @var{dir}; @};}.

@c ** -b option (radiusd)
@c ** --dbm option (radiusd)
@item -b
@itemx --dbm
Enable DBM support.

Config file equivalent: @code{usedbm yes;}.

@c ** -d (radiusd)
@c ** --config-directory option (radiusd)
@item -d @var{dir}
@itemx --config-directory=@var{dir}
@itemx --directory D
Specify alternate configuration directory. Default is @file{@value{RADDB}}.

@c ** -f option (radiusd)
@c ** --foreground option (radiusd)
@item -f
@itemx --foreground
Stay in foreground. We recommend to use it for debugging purposes only.

@c ** -i option (radiusd)
@c ** --ip-address
@item -i @var{ip}
@itemx --ip-address=@var{ip}
Specifies the @IP{} @command{radiusd} will listen on.
If this option is not specified, the program will listen on all
IP addresses, assigned to the machine it runs on.

Config file equivalent: @code{option @{ source-ip @var{ip}; @};}.

Note that @code{listen} statement in @file{raddb/config}
provides a better control over @IP{}es to listen on (@pxref{auth}, and
@pxref{acct}).

@c ** -l option (radiusd)
@c ** --logging-directory option (radiusd)
@item -l @var{dir}
@itemx --logging-directory @var{dir}
Specify alternate logging directory.

Config file equivalent: @code{option @{ log-dir @var{dir}; @};}.

@c ** -mb option (radiusd)
@c ** --mode b (radiusd)
@item -mb
@itemx --mode=b
``Builddbm'' mode. Builds a DBM version of a plaintext users database.
@ref{Builddbm}.

@c ** -mc option (radiusd)
@c ** --mode c (radiusd)
@item -mc
@itemx --mode=c
Check configuration files and exit. All errors are reported via usual
log channels.

@c ** -mt option (radiusd)
@c ** --mode t (radiusd)
@item -mt
@itemx --mode=t
Test mode. In this mode @command{radiusd} starts an interactive interpreter
which allows to test various aspects of its configuration.

@c ** -N option (radiusd)
@c ** --auth-only option (radiusd)
@item -N
@itemx --auth-only
Process only authentication requests.

@c ** -n option (radiusd)
@c ** --do-not-resolve option (radiusd)
@item -n
@itemx --do-not-resolve

Do not resolve IP addresses for diagnostic output. This can reduce the
amount of network traffic and speed up the server.

Config file equivalent: @code{option @{ resolve no @};}.

@c ** -p option (radiusd)
@c ** --port option (radiusd)
@item -p @var{portno}
@itemx --port @var{portno}
Listen the @sc{udp} port @var{portno}. The accounting port is computed
as @var{portno} + 1.

@c ** -P (radiusd)
@c ** --pid-file-dir (radiusd)
@item -P @var{dir}
@itemx --pid-file-dir=@var{dir}
Specifies the alternate path for the pidfile.

@c ** -S option (radiusd)
@c ** --log-stripped-names option (radiusd)
@item -S
@itemx --log-stripped-names
Log usernames stripped off any prefixes/suffixes.

Config file equivalent: @code{auth @{ strip-names yes @};}.

@c ** -s option (radiusd)
@c ** --single-process option (radiusd)
@item -s
@itemx --single-process
Run in single process mode. This is for debugging purposes only. We strongly
recommend @emph{against} using this option. Use it only when absolutely
necessary.

@c ** -v option (radiusd)
@c ** --version option (radiusd)
@item -v
@itemx --version
Display program version and compilation options.

@c ** -x option (radiusd)
@c ** --debug option (radiusd)
@item -x @var{debug_level}
@itemx --debug @var{debug_level}
Set debugging level. Argument is a comma-separated list of
assignments in the forms

@example
@var{module}
@var{module} = @var{level}
@end example

where @var{module} is the module name or any non-ambiguous assignment
thereof, and @var{level} is the debugging level in the range
0-100. @ref{Debugging}

Config file equivalent:
@example
logging @{
        category debug @{
                level @var{debug_level};
        @};
@};
@end example

@c ** -y option (radiusd)
@c ** --log-auth option (radiusd)
@item -y
@itemx --log-auth
Log authentications. With this option enabled, Radius will log any
authentication attempt into its log file @ref{Logging}.

Config file equivalent: @code{logging @{ category auth @{ detail yes;
@}; @}; }.

@item -z
@itemx --log-auth-pass
Log passwords along with authentication information. @emph{Do not use} this
option. It is @emph{very} insecure, since all users' passwords will be
echoed in the logfile. This option is provided only for debugging purposes.

Config file equivalent:
@example
logging @{
        category auth @{
                print-pass yes;
        @};
@};
@end example

@end table

@xref{config file}.

@c  LocalWords:  pid
