@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001,2002,2003 Free Software Foundation, Inc.
@c Written by Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radgrep, Radping, Radzap, Utility Programs
@section @command{radgrep}
@pindex radgrep

This utility allows one to quickly look up the user in the Radius
accounting database, using a regular expression match.
@command{radgrep} scans the output of @command{radwho} utility and
outputs only the lines that match given regular expressions.

@subheading Syntax
@command{radgrep} accepts two sets of options separated by @samp{--}
(double hyphen). The first subset is passed as the command line to the
@command{radwho} utility. The second one is passed to @command{grep}.

