@c This is part of the Radius manual.
@c Copyright (C) 1999-2025 Free Software Foundation, Inc.
@c Written by Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radping
@section @command{radping}
@pindex radping

This utility is a shell program that determines the user's
framed IP and runs @command{ping} on that address.

@subheading Syntax
@example
@group
radping @var{username}
radping -c @var{calling-station-id}
@end group
@end example

The second way of invoking the program allows one to use the calling station
@sc{id} to indicate the user.
