/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define uyyconst const
#else
#define uyyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN uyy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((uyy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE uyyrestart( uyyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct uyy_buffer_state *YY_BUFFER_STATE;

extern int uyyleng;
extern FILE *uyyin, *uyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		uyyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the uyyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define uyyless(n) \
	do \
		{ \
		/* Undo effects of setting up uyytext. */ \
		*uyy_cp = uyy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		uyy_c_buf_p = uyy_cp = uyy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up uyytext again */ \
		} \
	while ( 0 )

#define unput(c) uyyunput( c, uyytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int uyy_size_t;


struct uyy_buffer_state
	{
	FILE *uyy_input_file;

	char *uyy_ch_buf;		/* input buffer */
	char *uyy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	uyy_size_t uyy_buf_size;

	/* Number of characters read into uyy_ch_buf, not including EOB
	 * characters.
	 */
	int uyy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int uyy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int uyy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int uyy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int uyy_fill_buffer;

	int uyy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via uyyrestart()), so that the user can continue scanning by
	 * just pointing uyyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE uyy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER uyy_current_buffer


/* uyy_hold_char holds the character lost when uyytext is formed. */
static char uyy_hold_char;

static int uyy_n_chars;		/* number of characters read into uyy_ch_buf */


int uyyleng;

/* Points to current character in buffer. */
static char *uyy_c_buf_p = (char *) 0;
static int uyy_init = 1;		/* whether we need to initialize */
static int uyy_start = 0;	/* start state number */

/* Flag which is used to allow uyywrap()'s to do buffer switches
 * instead of setting up a fresh uyyin.  A bit of a hack ...
 */
static int uyy_did_buffer_switch_on_eof;

void uyyrestart YY_PROTO(( FILE *input_file ));

void uyy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void uyy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE uyy_create_buffer YY_PROTO(( FILE *file, int size ));
void uyy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void uyy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void uyy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER uyy_flush_buffer( uyy_current_buffer )

YY_BUFFER_STATE uyy_scan_buffer YY_PROTO(( char *base, uyy_size_t size ));
YY_BUFFER_STATE uyy_scan_string YY_PROTO(( uyyconst char *uyy_str ));
YY_BUFFER_STATE uyy_scan_bytes YY_PROTO(( uyyconst char *bytes, int len ));

static void *uyy_flex_alloc YY_PROTO(( uyy_size_t ));
static void *uyy_flex_realloc YY_PROTO(( void *, uyy_size_t ));
static void uyy_flex_free YY_PROTO(( void * ));

#define uyy_new_buffer uyy_create_buffer

#define uyy_set_interactive(is_interactive) \
	{ \
	if ( ! uyy_current_buffer ) \
		uyy_current_buffer = uyy_create_buffer( uyyin, YY_BUF_SIZE ); \
	uyy_current_buffer->uyy_is_interactive = is_interactive; \
	}

#define uyy_set_bol(at_bol) \
	{ \
	if ( ! uyy_current_buffer ) \
		uyy_current_buffer = uyy_create_buffer( uyyin, YY_BUF_SIZE ); \
	uyy_current_buffer->uyy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (uyy_current_buffer->uyy_at_bol)

typedef unsigned char YY_CHAR;
FILE *uyyin = (FILE *) 0, *uyyout = (FILE *) 0;
typedef int uyy_state_type;
extern char *uyytext;
#define uyytext_ptr uyytext

static uyy_state_type uyy_get_previous_state YY_PROTO(( void ));
static uyy_state_type uyy_try_NUL_trans YY_PROTO(( uyy_state_type current_state ));
static int uyy_get_next_buffer YY_PROTO(( void ));
static void uyy_fatal_error YY_PROTO(( uyyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up uyytext.
 */
#define YY_DO_BEFORE_ACTION \
	uyytext_ptr = uyy_bp; \
	uyyleng = (int) (uyy_cp - uyy_bp); \
	uyy_hold_char = *uyy_cp; \
	*uyy_cp = '\0'; \
	uyy_c_buf_p = uyy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
static uyyconst short int uyy_accept[75] =
    {   0,
        0,    0,    0,    0,   36,   34,   26,   27,    7,   34,
        2,   34,    7,    7,   31,   28,   30,    7,   35,   18,
       25,   35,   26,    7,   29,    0,   10,    8,    0,    2,
        1,    0,    3,    7,    7,   33,   32,    7,    0,   18,
       25,    0,   19,   17,   22,    0,   11,    9,   14,    0,
        7,    7,    7,   23,   20,   15,   12,    7,    7,    4,
       24,   21,   16,   13,    7,    7,    7,    7,    5,    7,
        6,    5,    5,    0
    } ;

static uyyconst int uyy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    1,    1,    1,
        1,    1,    8,    1,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   12,   12,    1,    1,   13,
       14,   15,    1,    1,   16,   16,   16,   16,   16,   16,
        9,    9,    9,    9,    9,   17,    9,   18,    9,    9,
        9,    9,    9,    9,   19,    9,    9,   20,    9,    9,
        1,   21,    1,    1,    9,    1,   16,   16,   16,   16,

       16,   16,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   20,
        9,    9,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static uyyconst int uyy_meta[22] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    2,    2,
        2,    3,    1,    2,    1,    2,    2,    2,    2,    2,
        1
    } ;

static uyyconst short int uyy_base[83] =
    {   0,
        0,    0,   19,   20,  137,  138,  134,  138,  121,   23,
      131,  130,  118,   35,  117,  138,  116,   13,   30,  138,
      138,   28,  127,  114,  138,   31,  138,  138,   39,  124,
      138,  123,  138,   42,   18,  138,  138,   41,   57,  138,
      138,   54,  138,  138,  114,   52,  138,  138,  113,   55,
       65,   26,  106,  111,   68,   74,   70,   58,   61,   66,
      138,  138,  138,  138,   77,   51,   79,   81,   86,   33,
      138,   84,   88,  138,  100,  102,  105,  108,  111,  114,
      117,  119
    } ;

static uyyconst short int uyy_def[83] =
    {   0,
       74,    1,   75,   75,   74,   74,   74,   74,   76,   77,
       78,   79,   76,   76,   74,   74,   74,   76,   80,   74,
       74,   81,   74,   76,   74,   77,   74,   74,   82,   78,
       74,   79,   74,   76,   14,   74,   74,   76,   80,   74,
       74,   81,   74,   74,   74,   74,   74,   74,   74,   74,
       14,   14,   38,   74,   74,   74,   74,   34,   51,   38,
       74,   74,   74,   74,   51,   52,   34,   65,   34,   52,
       74,   69,   69,    0,   74,   74,   74,   74,   74,   74,
       74,   74
    } ;

static uyyconst short int uyy_nxt[160] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,    6,   13,   13,
       14,   14,   15,   16,   17,   13,   13,   18,   13,   13,
        6,   20,   20,   21,   21,   27,   74,   28,   52,   52,
       44,   38,   40,   27,   41,   28,   24,   24,   45,   22,
       22,   48,   67,   29,   34,   35,   35,   46,   74,   49,
       42,   29,   51,   51,   74,   74,   44,   53,   50,   40,
       58,   41,   55,   55,   45,   57,   57,   55,   65,   65,
       57,   66,   66,   46,   58,   59,   59,   42,   62,   62,
       64,   64,   24,   62,   63,   64,   67,   68,   68,   69,
       69,   70,   70,   71,   73,   73,   72,   72,   24,   24,

       19,   19,   19,   24,   24,   26,   26,   26,   30,   30,
       30,   32,   32,   32,   39,   39,   39,   43,   43,   47,
       47,   61,   60,   56,   54,   33,   31,   74,   23,   37,
       36,   74,   33,   31,   25,   23,   74,    5,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74
    } ;

static uyyconst short int uyy_chk[160] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,   10,   18,   10,   35,   35,
       22,   18,   19,   26,   19,   26,   52,   52,   22,    3,
        4,   29,   70,   10,   14,   14,   14,   22,   14,   29,
       19,   26,   34,   34,   38,   34,   42,   38,   29,   39,
       66,   39,   46,   46,   42,   50,   50,   46,   58,   58,
       50,   59,   59,   42,   51,   51,   51,   39,   55,   55,
       57,   57,   60,   55,   56,   57,   65,   65,   65,   67,
       67,   68,   68,   69,   72,   72,   69,   69,   73,   73,

       75,   75,   75,   76,   76,   77,   77,   77,   78,   78,
       78,   79,   79,   79,   80,   80,   80,   81,   81,   82,
       82,   54,   53,   49,   45,   32,   30,   24,   23,   17,
       15,   13,   12,   11,    9,    7,    5,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74
    } ;

static uyy_state_type uyy_last_accepting_state;
static char *uyy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define uyymore() uyymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *uyytext;
#line 1 "users.l"
#define INITIAL 0
/* This file is part of GNU Radius.
   Copyright (C) 2000,2001,2002,2003,2004,2005,
   2007,2008 Free Software Foundation, Inc.

   Written by Sergey Poznyakoff
  
   GNU Radius is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.
  
   GNU Radius is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
  
   You should have received a copy of the GNU General Public
   License along with GNU Radius; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301 USA. */
#define in_string 1

#line 25 "users.l"
 
#if defined(HAVE_CONFIG_H)        
# include <config.h>
#endif
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <netinet/in.h>
                 
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <fcntl.h>
#include <time.h>
#include <ctype.h>
#include <unistd.h>
#include <signal.h>
#include <errno.h>
#include <sys/wait.h>

#include <radlib.h>
#include <users_gram.h>

extern void grad_enable_rule_debug(int);
extern int uyyerror(char *s); 
static char *addstring();
static char *addquote();
static int preproc();
static void read_number(char *text, int len, int base);
static void grow_backslash_num(grad_slist_t slist, char *text, int len,
			       int base);

static grad_slist_t slist;   /* Slist for keeping string values */ 
grad_locus_t grad_parser_source_locus;
ino_t source_inode;          /* Inode of the current source (for preventing
                                recursive inclusion */

        
#ifdef FLEX_SCANNER
#define xinput() (uyyin ? getc(uyyin) : EOF)
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size)  do { \
        int i;                                  \
        for (i = 0; i < max_size; i++) {        \
                int ch = xinput();              \
                if (ch == EOF)                  \
                        break;                  \
                buf[i] = ch;                    \
        }                                       \
        result = i;                             \
} while (0) 
#define LEX_BUFFER_STATE YY_BUFFER_STATE
#define SET_BUFFER_STATE(s) do { \
        (s) = YY_CURRENT_BUFFER; \
        uyy_switch_to_buffer(uyy_create_buffer(uyyin, YY_BUF_SIZE)); \
} while (0)
#define RESTORE_BUFFER_STATE(s) do { \
        uyy_delete_buffer(YY_CURRENT_BUFFER); \
        uyy_switch_to_buffer(s); \
} while (0)

#else
/* AT&T Lex */
                                               
static void lex_set_buffer(FILE *fp);
static void lex_delete_buffer(LEX_BUFFER_STATE buf);
static int xinput(); 
static int xunput();
        
#undef unput
#define unput(c) xunput(c)
#undef input
#define input() xinput()

#define LEX_BUF_SIZE 16384
#define LEX_PUTBACK_SIZE 32
                                               
typedef struct {
        FILE *uyyin;
        char *buffer;
        size_t bufsize;
        size_t level;
        char *ptr;
        char *putback;
        size_t pb_size;
        size_t pb_level;
} LEX_BUFFER_STATE;
LEX_BUFFER_STATE current_buffer;
 
#define SET_BUFFER_STATE(s) do { \
        (s) = current_buffer;    \
        lex_set_buffer(uyyin);    \
} while (0)
#define RESTORE_BUFFER_STATE(s) do { \
        lex_delete_buffer(current_buffer); \
        current_buffer = (s); \
        uyyin = current_buffer.uyyin;  \
} while (0)
                                    
void
lex_set_buffer(FILE *fp)
{
        char *buf;
        size_t size;
        
        for (size = LEX_BUF_SIZE; size > 1; size /= 2)
                if (buf = grad_malloc(size))
                        break;
        if (!buf) {
                grad_log(GRAD_LOG_CRIT, _("not enough memory"));
                abort();
        }

        current_buffer.uyyin = uyyin;
        current_buffer.buffer = buf;
        current_buffer.bufsize = size;
        current_buffer.level = 0;
        current_buffer.ptr = current_buffer.buffer;
        current_buffer.pb_size = current_buffer.pb_level = 0;
        current_buffer.putback = NULL;
}
                
void
lex_delete_buffer(LEX_BUFFER_STATE buf)
{
        grad_free(buf.buffer);
        if (buf.putback)
                grad_free(buf.putback);
}

int
xinput()
{
        if (!uyyin)
                return EOF;
        if (current_buffer.pb_level) 
                return current_buffer.putback[--current_buffer.pb_level];

        if (current_buffer.level <= 0) {
                int n;

                if (feof(uyyin))
                        return 0;
                n = fread(current_buffer.buffer, 1,
                          current_buffer.bufsize, uyyin);
                if (n <= 0)
                        return 0;
                current_buffer.level = n;
                current_buffer.ptr = current_buffer.buffer;
        }
        current_buffer.level--;
        return *current_buffer.ptr++;
}

int
xunput(int c)
{
        if (current_buffer.pb_level == current_buffer.pb_size) {
                char *putback;
                current_buffer.pb_size += LEX_PUTBACK_SIZE;
                putback = grad_emalloc(current_buffer.pb_size);
                memcpy(putback, current_buffer.putback,
                       current_buffer.pb_level);
                grad_free(current_buffer.putback);
                current_buffer.putback = putback;
        }
        current_buffer.putback[current_buffer.pb_level++] = c;
        return c;
}
                
#endif                                         

struct buffer_ctx {
        struct buffer_ctx *prev;
	grad_locus_t loc;
        ino_t i_node;
        FILE *uyyin;
        LEX_BUFFER_STATE state;
};

static struct buffer_ctx *context_stack;

static struct buffer_ctx *ctx_lookup(ino_t ino);
static int push_source(char *name);
static int pop_source();

struct buffer_ctx *
ctx_lookup(ino_t ino)
{
        struct buffer_ctx *ctx;

        for (ctx = context_stack; ctx; ctx = ctx->prev)
                if (ctx->i_node == ino)
                        break;
        return ctx;
}
        
int
push_source(char *name)
{
        FILE *fp;
        struct buffer_ctx *ctx;
        struct stat st;
        
        if (stat(name, &st)) {
                grad_log(GRAD_LOG_ERR|GRAD_LOG_PERROR,
		         _("can't stat `%s'"), name);
                uyyerror("can't include file");
                return 1;
        }

        if (grad_parser_source_locus.file && st.st_ino == source_inode) {
                uyyerror("recursive inclusion");
                return 1;
        }
        if (ctx = ctx_lookup(st.st_ino)) {
                uyyerror("recursive inclusion");
                if (ctx->prev)
                        grad_log_loc(GRAD_LOG_ERR, &ctx->prev->loc,
				     _("`%s' already included here"),
				     name);
                else
                        grad_log(GRAD_LOG_ERR, 
                                 _("`%s' already included at top level"),
                                 name);
                return 1;
        }
                
        fp = fopen(name, "r");
        if (!fp) {
                grad_log(GRAD_LOG_ERR|GRAD_LOG_PERROR,
                         _("can't open `%s'"),  name);
                uyyerror("can't include file");
                return 1;
        }

        /* Push current context */
        if (grad_parser_source_locus.file) {
                ctx = grad_emalloc(sizeof(*ctx));
                ctx->loc = grad_parser_source_locus;
                ctx->i_node = source_inode;
                ctx->uyyin = uyyin;
                ctx->prev = context_stack;
                context_stack = ctx;

                /* Switch to the new context */
                uyyin = fp;
                SET_BUFFER_STATE(ctx->state);
        } else {
#ifdef FLEX_SCANNER
                uyyrestart(fp);
#else           
                uyyin = fp;
                lex_set_buffer(uyyin);
#endif
        }
        grad_parser_source_locus.file = name;
        grad_parser_source_locus.line = 1;
        source_inode = st.st_ino;
        return 0;
}

int
pop_source()
{
        struct buffer_ctx *ctx;

        if (!uyyin) 
                return 1;
	
        fclose(uyyin);
#ifndef FLEX_SCANNER
        lex_delete_buffer(current_buffer);
#endif
        if (!context_stack) {
		uyyin = NULL;
                return 1;
        }
	/* Restore previous context */
        grad_parser_source_locus = context_stack->loc;
        source_inode = context_stack->i_node;
        RESTORE_BUFFER_STATE(context_stack->state);
        ctx = context_stack->prev;
        grad_free(context_stack);
        context_stack = ctx;
        return 0;
}
        
#line 733 "users_lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int uyywrap YY_PROTO(( void ));
#else
extern int uyywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void uyyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef uyytext_ptr
static void uyy_flex_strncpy YY_PROTO(( char *, uyyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int uyy_flex_strlen YY_PROTO(( uyyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int uyyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int uyy_start_stack_ptr = 0;
static int uyy_start_stack_depth = 0;
static int *uyy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void uyy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void uyy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int uyy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( uyytext, uyyleng, 1, uyyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( uyy_current_buffer->uyy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( uyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( uyyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, uyyin )) == 0) \
		  && ferror( uyyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "uyyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef uyyterminate
#define uyyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) uyy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int uyylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after uyytext and uyyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register uyy_state_type uyy_current_state;
	register char *uyy_cp = NULL, *uyy_bp = NULL;
	register int uyy_act;

#line 323 "users.l"

#line 886 "users_lex.c"

	if ( uyy_init )
		{
		uyy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! uyy_start )
			uyy_start = 1;	/* first start state */

		if ( ! uyyin )
			uyyin = stdin;

		if ( ! uyyout )
			uyyout = stdout;

		if ( ! uyy_current_buffer )
			uyy_current_buffer =
				uyy_create_buffer( uyyin, YY_BUF_SIZE );

		uyy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		uyy_cp = uyy_c_buf_p;

		/* Support of uyytext. */
		*uyy_cp = uyy_hold_char;

		/* uyy_bp points to the position in uyy_ch_buf of the start of
		 * the current run.
		 */
		uyy_bp = uyy_cp;

		uyy_current_state = uyy_start;
uyy_match:
		do
			{
			register YY_CHAR uyy_c = uyy_ec[YY_SC_TO_UI(*uyy_cp)];
			if ( uyy_accept[uyy_current_state] )
				{
				uyy_last_accepting_state = uyy_current_state;
				uyy_last_accepting_cpos = uyy_cp;
				}
			while ( uyy_chk[uyy_base[uyy_current_state] + uyy_c] != uyy_current_state )
				{
				uyy_current_state = (int) uyy_def[uyy_current_state];
				if ( uyy_current_state >= 75 )
					uyy_c = uyy_meta[(unsigned int) uyy_c];
				}
			uyy_current_state = uyy_nxt[uyy_base[uyy_current_state] + (unsigned int) uyy_c];
			++uyy_cp;
			}
		while ( uyy_base[uyy_current_state] != 138 );

uyy_find_action:
		uyy_act = uyy_accept[uyy_current_state];
		if ( uyy_act == 0 )
			{ /* have to back up */
			uyy_cp = uyy_last_accepting_cpos;
			uyy_current_state = uyy_last_accepting_state;
			uyy_act = uyy_accept[uyy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( uyy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*uyy_cp = uyy_hold_char;
			uyy_cp = uyy_last_accepting_cpos;
			uyy_current_state = uyy_last_accepting_state;
			goto uyy_find_action;

case 1:
YY_RULE_SETUP
#line 324 "users.l"
{
          if (strncmp(uyytext+1, "debug", 5) == 0)
                  grad_enable_rule_debug(1);
          grad_parser_source_locus.line++; /* a comment */
        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 329 "users.l"
/* end-of-file comment */;
	YY_BREAK
case 3:
*uyy_cp = uyy_hold_char; /* undo effects of setting up uyytext */
uyy_c_buf_p = uyy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up uyytext again */
YY_RULE_SETUP
#line 330 "users.l"
preproc();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 331 "users.l"
return NUL;
	YY_BREAK
case 5:
#line 333 "users.l"
case 6:
YY_RULE_SETUP
#line 333 "users.l"
{
          uyylval.string = addstring(uyytext);
          return STRING;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 337 "users.l"
{
          uyylval.string = addstring(uyytext);
          return STRING;
        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 341 "users.l"
{
          uyylval.string = addquote(uyytext);
          return QUOTE;
        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 345 "users.l"
{
          BEGIN(in_string);
          if (uyyleng > 3)
		  grad_slist_append(slist, uyytext+1, uyyleng-3);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 350 "users.l"
{
          BEGIN(INITIAL);
          uyyerror("unterminated character string");
          return BOGUS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 355 "users.l"
{
          BEGIN(in_string);
          if (uyyleng > 3)
                 grad_slist_append(slist, uyytext+1, uyyleng-3);
          grad_slist_append_char(slist, grad_decode_backslash(uyytext[uyyleng-1]));
}
	YY_BREAK
case 12:
#line 362 "users.l"
case 13:
YY_RULE_SETUP
#line 362 "users.l"
{
	  BEGIN(in_string);
	  grow_backslash_num(slist, uyytext + 1, uyyleng - 1, 16);
}
	YY_BREAK
case 14:
#line 367 "users.l"
case 15:
#line 368 "users.l"
case 16:
YY_RULE_SETUP
#line 368 "users.l"
{
          BEGIN(in_string);
          grow_backslash_num(slist, uyytext + 1, uyyleng - 1, 8); 
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 372 "users.l"
{
          grad_slist_append(slist, uyytext, uyyleng-2);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 375 "users.l"
{
          BEGIN(INITIAL);
          grad_slist_clear(slist);
          uyyerror("unterminated character string");
          return BOGUS;
}         
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 381 "users.l"
{
          if (uyyleng > 2)
                   grad_slist_append(slist, uyytext, uyyleng-2);
          grad_slist_append_char(slist, grad_decode_backslash(uyytext[uyyleng-1]));
}
	YY_BREAK
case 20:
#line 387 "users.l"
case 21:
YY_RULE_SETUP
#line 387 "users.l"
{
	  grow_backslash_num(slist, uyytext, uyyleng, 16);
}
	YY_BREAK
case 22:
#line 391 "users.l"
case 23:
#line 392 "users.l"
case 24:
YY_RULE_SETUP
#line 392 "users.l"
{
          grow_backslash_num(slist, uyytext, uyyleng, 8);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 395 "users.l"
{
          BEGIN(INITIAL);
          grad_slist_append(slist, uyytext, uyyleng-1);
          grad_slist_append_char(slist, 0);
          uyylval.string = grad_slist_finish(slist);
          return QUOTE;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 402 "users.l"
;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 403 "users.l"
{
          grad_parser_source_locus.line++;
        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 406 "users.l"
return EQ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 407 "users.l"
return NE;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 408 "users.l"
return GT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 409 "users.l"
return LT;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 410 "users.l"
return GE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 411 "users.l"
return LE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 412 "users.l"
return uyytext[0];
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 414 "users.l"
ECHO;
	YY_BREAK
#line 1181 "users_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(in_string):
	uyyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int uyy_amount_of_matched_text = (int) (uyy_cp - uyytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*uyy_cp = uyy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( uyy_current_buffer->uyy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed uyyin at a new source and called
			 * uyylex().  If so, then we have to assure
			 * consistency between uyy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			uyy_n_chars = uyy_current_buffer->uyy_n_chars;
			uyy_current_buffer->uyy_input_file = uyyin;
			uyy_current_buffer->uyy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for uyy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since uyy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( uyy_c_buf_p <= &uyy_current_buffer->uyy_ch_buf[uyy_n_chars] )
			{ /* This was really a NUL. */
			uyy_state_type uyy_next_state;

			uyy_c_buf_p = uyytext_ptr + uyy_amount_of_matched_text;

			uyy_current_state = uyy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * uyy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			uyy_next_state = uyy_try_NUL_trans( uyy_current_state );

			uyy_bp = uyytext_ptr + YY_MORE_ADJ;

			if ( uyy_next_state )
				{
				/* Consume the NUL. */
				uyy_cp = ++uyy_c_buf_p;
				uyy_current_state = uyy_next_state;
				goto uyy_match;
				}

			else
				{
				uyy_cp = uyy_c_buf_p;
				goto uyy_find_action;
				}
			}

		else switch ( uyy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				uyy_did_buffer_switch_on_eof = 0;

				if ( uyywrap() )
					{
					/* Note: because we've taken care in
					 * uyy_get_next_buffer() to have set up
					 * uyytext, we can now set up
					 * uyy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					uyy_c_buf_p = uyytext_ptr + YY_MORE_ADJ;

					uyy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! uyy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				uyy_c_buf_p =
					uyytext_ptr + uyy_amount_of_matched_text;

				uyy_current_state = uyy_get_previous_state();

				uyy_cp = uyy_c_buf_p;
				uyy_bp = uyytext_ptr + YY_MORE_ADJ;
				goto uyy_match;

			case EOB_ACT_LAST_MATCH:
				uyy_c_buf_p =
				&uyy_current_buffer->uyy_ch_buf[uyy_n_chars];

				uyy_current_state = uyy_get_previous_state();

				uyy_cp = uyy_c_buf_p;
				uyy_bp = uyytext_ptr + YY_MORE_ADJ;
				goto uyy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of uyylex */


/* uyy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int uyy_get_next_buffer()
	{
	register char *dest = uyy_current_buffer->uyy_ch_buf;
	register char *source = uyytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( uyy_c_buf_p > &uyy_current_buffer->uyy_ch_buf[uyy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( uyy_current_buffer->uyy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( uyy_c_buf_p - uyytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (uyy_c_buf_p - uyytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( uyy_current_buffer->uyy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		uyy_current_buffer->uyy_n_chars = uyy_n_chars = 0;

	else
		{
		int num_to_read =
			uyy_current_buffer->uyy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = uyy_current_buffer;

			int uyy_c_buf_p_offset =
				(int) (uyy_c_buf_p - b->uyy_ch_buf);

			if ( b->uyy_is_our_buffer )
				{
				int new_size = b->uyy_buf_size * 2;

				if ( new_size <= 0 )
					b->uyy_buf_size += b->uyy_buf_size / 8;
				else
					b->uyy_buf_size *= 2;

				b->uyy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					uyy_flex_realloc( (void *) b->uyy_ch_buf,
							 b->uyy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->uyy_ch_buf = 0;

			if ( ! b->uyy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			uyy_c_buf_p = &b->uyy_ch_buf[uyy_c_buf_p_offset];

			num_to_read = uyy_current_buffer->uyy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&uyy_current_buffer->uyy_ch_buf[number_to_move]),
			uyy_n_chars, num_to_read );

		uyy_current_buffer->uyy_n_chars = uyy_n_chars;
		}

	if ( uyy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			uyyrestart( uyyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			uyy_current_buffer->uyy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	uyy_n_chars += number_to_move;
	uyy_current_buffer->uyy_ch_buf[uyy_n_chars] = YY_END_OF_BUFFER_CHAR;
	uyy_current_buffer->uyy_ch_buf[uyy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	uyytext_ptr = &uyy_current_buffer->uyy_ch_buf[0];

	return ret_val;
	}


/* uyy_get_previous_state - get the state just before the EOB char was reached */

static uyy_state_type uyy_get_previous_state()
	{
	register uyy_state_type uyy_current_state;
	register char *uyy_cp;

	uyy_current_state = uyy_start;

	for ( uyy_cp = uyytext_ptr + YY_MORE_ADJ; uyy_cp < uyy_c_buf_p; ++uyy_cp )
		{
		register YY_CHAR uyy_c = (*uyy_cp ? uyy_ec[YY_SC_TO_UI(*uyy_cp)] : 1);
		if ( uyy_accept[uyy_current_state] )
			{
			uyy_last_accepting_state = uyy_current_state;
			uyy_last_accepting_cpos = uyy_cp;
			}
		while ( uyy_chk[uyy_base[uyy_current_state] + uyy_c] != uyy_current_state )
			{
			uyy_current_state = (int) uyy_def[uyy_current_state];
			if ( uyy_current_state >= 75 )
				uyy_c = uyy_meta[(unsigned int) uyy_c];
			}
		uyy_current_state = uyy_nxt[uyy_base[uyy_current_state] + (unsigned int) uyy_c];
		}

	return uyy_current_state;
	}


/* uyy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = uyy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static uyy_state_type uyy_try_NUL_trans( uyy_state_type uyy_current_state )
#else
static uyy_state_type uyy_try_NUL_trans( uyy_current_state )
uyy_state_type uyy_current_state;
#endif
	{
	register int uyy_is_jam;
	register char *uyy_cp = uyy_c_buf_p;

	register YY_CHAR uyy_c = 1;
	if ( uyy_accept[uyy_current_state] )
		{
		uyy_last_accepting_state = uyy_current_state;
		uyy_last_accepting_cpos = uyy_cp;
		}
	while ( uyy_chk[uyy_base[uyy_current_state] + uyy_c] != uyy_current_state )
		{
		uyy_current_state = (int) uyy_def[uyy_current_state];
		if ( uyy_current_state >= 75 )
			uyy_c = uyy_meta[(unsigned int) uyy_c];
		}
	uyy_current_state = uyy_nxt[uyy_base[uyy_current_state] + (unsigned int) uyy_c];
	uyy_is_jam = (uyy_current_state == 74);

	return uyy_is_jam ? 0 : uyy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void uyyunput( int c, register char *uyy_bp )
#else
static void uyyunput( c, uyy_bp )
int c;
register char *uyy_bp;
#endif
	{
	register char *uyy_cp = uyy_c_buf_p;

	/* undo effects of setting up uyytext */
	*uyy_cp = uyy_hold_char;

	if ( uyy_cp < uyy_current_buffer->uyy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = uyy_n_chars + 2;
		register char *dest = &uyy_current_buffer->uyy_ch_buf[
					uyy_current_buffer->uyy_buf_size + 2];
		register char *source =
				&uyy_current_buffer->uyy_ch_buf[number_to_move];

		while ( source > uyy_current_buffer->uyy_ch_buf )
			*--dest = *--source;

		uyy_cp += (int) (dest - source);
		uyy_bp += (int) (dest - source);
		uyy_current_buffer->uyy_n_chars =
			uyy_n_chars = uyy_current_buffer->uyy_buf_size;

		if ( uyy_cp < uyy_current_buffer->uyy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--uyy_cp = (char) c;


	uyytext_ptr = uyy_bp;
	uyy_hold_char = *uyy_cp;
	uyy_c_buf_p = uyy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int uyyinput()
#else
static int input()
#endif
	{
	int c;

	*uyy_c_buf_p = uyy_hold_char;

	if ( *uyy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* uyy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( uyy_c_buf_p < &uyy_current_buffer->uyy_ch_buf[uyy_n_chars] )
			/* This was really a NUL. */
			*uyy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = uyy_c_buf_p - uyytext_ptr;
			++uyy_c_buf_p;

			switch ( uyy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because uyy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					uyyrestart( uyyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( uyywrap() )
						return EOF;

					if ( ! uyy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return uyyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					uyy_c_buf_p = uyytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) uyy_c_buf_p;	/* cast for 8-bit char's */
	*uyy_c_buf_p = '\0';	/* preserve uyytext */
	uyy_hold_char = *++uyy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void uyyrestart( FILE *input_file )
#else
void uyyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! uyy_current_buffer )
		uyy_current_buffer = uyy_create_buffer( uyyin, YY_BUF_SIZE );

	uyy_init_buffer( uyy_current_buffer, input_file );
	uyy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void uyy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void uyy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( uyy_current_buffer == new_buffer )
		return;

	if ( uyy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*uyy_c_buf_p = uyy_hold_char;
		uyy_current_buffer->uyy_buf_pos = uyy_c_buf_p;
		uyy_current_buffer->uyy_n_chars = uyy_n_chars;
		}

	uyy_current_buffer = new_buffer;
	uyy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (uyywrap()) processing, but the only time this flag
	 * is looked at is after uyywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	uyy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void uyy_load_buffer_state( void )
#else
void uyy_load_buffer_state()
#endif
	{
	uyy_n_chars = uyy_current_buffer->uyy_n_chars;
	uyytext_ptr = uyy_c_buf_p = uyy_current_buffer->uyy_buf_pos;
	uyyin = uyy_current_buffer->uyy_input_file;
	uyy_hold_char = *uyy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE uyy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE uyy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) uyy_flex_alloc( sizeof( struct uyy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in uyy_create_buffer()" );

	b->uyy_buf_size = size;

	/* uyy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->uyy_ch_buf = (char *) uyy_flex_alloc( b->uyy_buf_size + 2 );
	if ( ! b->uyy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in uyy_create_buffer()" );

	b->uyy_is_our_buffer = 1;

	uyy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void uyy_delete_buffer( YY_BUFFER_STATE b )
#else
void uyy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == uyy_current_buffer )
		uyy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->uyy_is_our_buffer )
		uyy_flex_free( (void *) b->uyy_ch_buf );

	uyy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void uyy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void uyy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	uyy_flush_buffer( b );

	b->uyy_input_file = file;
	b->uyy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->uyy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->uyy_is_interactive = 0;
#else
	b->uyy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void uyy_flush_buffer( YY_BUFFER_STATE b )
#else
void uyy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->uyy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->uyy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->uyy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->uyy_buf_pos = &b->uyy_ch_buf[0];

	b->uyy_at_bol = 1;
	b->uyy_buffer_status = YY_BUFFER_NEW;

	if ( b == uyy_current_buffer )
		uyy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE uyy_scan_buffer( char *base, uyy_size_t size )
#else
YY_BUFFER_STATE uyy_scan_buffer( base, size )
char *base;
uyy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) uyy_flex_alloc( sizeof( struct uyy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in uyy_scan_buffer()" );

	b->uyy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->uyy_buf_pos = b->uyy_ch_buf = base;
	b->uyy_is_our_buffer = 0;
	b->uyy_input_file = 0;
	b->uyy_n_chars = b->uyy_buf_size;
	b->uyy_is_interactive = 0;
	b->uyy_at_bol = 1;
	b->uyy_fill_buffer = 0;
	b->uyy_buffer_status = YY_BUFFER_NEW;

	uyy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE uyy_scan_string( uyyconst char *uyy_str )
#else
YY_BUFFER_STATE uyy_scan_string( uyy_str )
uyyconst char *uyy_str;
#endif
	{
	int len;
	for ( len = 0; uyy_str[len]; ++len )
		;

	return uyy_scan_bytes( uyy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE uyy_scan_bytes( uyyconst char *bytes, int len )
#else
YY_BUFFER_STATE uyy_scan_bytes( bytes, len )
uyyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	uyy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) uyy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in uyy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = uyy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in uyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->uyy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void uyy_push_state( int new_state )
#else
static void uyy_push_state( new_state )
int new_state;
#endif
	{
	if ( uyy_start_stack_ptr >= uyy_start_stack_depth )
		{
		uyy_size_t new_size;

		uyy_start_stack_depth += YY_START_STACK_INCR;
		new_size = uyy_start_stack_depth * sizeof( int );

		if ( ! uyy_start_stack )
			uyy_start_stack = (int *) uyy_flex_alloc( new_size );

		else
			uyy_start_stack = (int *) uyy_flex_realloc(
					(void *) uyy_start_stack, new_size );

		if ( ! uyy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	uyy_start_stack[uyy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void uyy_pop_state()
	{
	if ( --uyy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(uyy_start_stack[uyy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int uyy_top_state()
	{
	return uyy_start_stack[uyy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void uyy_fatal_error( uyyconst char msg[] )
#else
static void uyy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine uyyless() so it works in section 3 code. */

#undef uyyless
#define uyyless(n) \
	do \
		{ \
		/* Undo effects of setting up uyytext. */ \
		uyytext[uyyleng] = uyy_hold_char; \
		uyy_c_buf_p = uyytext + n; \
		uyy_hold_char = *uyy_c_buf_p; \
		*uyy_c_buf_p = '\0'; \
		uyyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef uyytext_ptr
#ifdef YY_USE_PROTOS
static void uyy_flex_strncpy( char *s1, uyyconst char *s2, int n )
#else
static void uyy_flex_strncpy( s1, s2, n )
char *s1;
uyyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int uyy_flex_strlen( uyyconst char *s )
#else
static int uyy_flex_strlen( s )
uyyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *uyy_flex_alloc( uyy_size_t size )
#else
static void *uyy_flex_alloc( size )
uyy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *uyy_flex_realloc( void *ptr, uyy_size_t size )
#else
static void *uyy_flex_realloc( ptr, size )
void *ptr;
uyy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void uyy_flex_free( void *ptr )
#else
static void uyy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	uyylex();
	return 0;
	}
#endif
#line 414 "users.l"


int
uyywrap()
{
        return pop_source();
}

char *
addstring(char *s)
{
        int length = strlen(s);
        grad_slist_append(slist, s, length+1);
        return grad_slist_finish(slist);
}
        
char *
addquote(char *s)
{
        int length = strlen(s);
        if (length-2 > 0)
                grad_slist_append(slist, s+1, length-2);
        grad_slist_append_char(slist, 0);
        return grad_slist_finish(slist);
}

int
grad_parser_lex_init(char *name)
{
	int rc;

        slist = grad_slist_create();
        
        context_stack = NULL;
        grad_parser_source_locus.file = NULL;
        rc = push_source(name);
	if (rc)	
		grad_slist_free(&slist);
	return rc;
}

void
grad_parser_lex_finish()
{
        grad_slist_free(&slist);
#ifdef FLEX_SCANNER     
        uyy_delete_buffer(YY_CURRENT_BUFFER); 
#endif
        uyyin = NULL;
}

/* A rudimentary attempt to synchronize input after an error.
 * It is based on the assumption that only user names start
 * at column 0
 */
int
grad_parser_lex_sync()
{
        int c;
        while ((c = input()) > 0) {
                if (c == '\n') {
                        do {
                                c = input();
                        } while (c == '\n');
                        if (!isspace(c)) {
                                if (c)
                                        unput(c);
				break;
                        } 
                }
        }
	return c;
}

#define isws(c) ((c) == ' ' || (c) == '\t')

/* Parse pre-processor directive. Currently supported directives are:
   $                  (Empty directive.)
   $INCLUDE filename
   $DEBUG [yYnN01] */
int
preproc()
{
        char *sp, *p;
        char *endp;
        int len;
        
        endp = uyytext + uyyleng;
        for (sp = uyytext+1; sp < endp && isws(*sp); sp++)
                ;

        if (sp >= endp) 
                return 0;

        for (p = sp; p < endp && !isws(*p); p++)
                ;
        if (sp >= endp) 
                return 0;
        len = p - sp;

        for (; p < endp && isws(*p); p++)
                ;

        if (len == 7 && strncmp(sp, "INCLUDE", 7) == 0) {
                char *name;

                sp = p;
                for (; p < endp && !isws(*p); p++)
                        ;
                len = p - sp;
                if (len == 0) {
                        uyyerror("empty file name");
                        return 1;
                }
                
                if (*sp != '/') {
                        /* append standard configuration directory path */
                        grad_slist_append(slist, grad_config_dir, strlen(grad_config_dir));
                        grad_slist_append_char(slist, '/');
                }
        
                grad_slist_append(slist, sp, len);
                grad_slist_append_char(slist, 0);
                name = grad_slist_finish(slist);
                return push_source(name);
        } else if (len == 5 && strncmp(sp, "DEBUG", 5) == 0) {
                int v;
                
                switch (*p) {
                case 0:
                case 'y':
                case 'Y':
                case '1':
                        v = 1;
                        break;
                case 'n':
                case 'N':
                case '0':
                        v = 0;
                        break;
                }
                grad_enable_rule_debug(v);
                return 0;
        }
        return 1;
}

void
grow_backslash_num(grad_slist_t slist, char *text, int len, int base)
{
	char *p = strchr(text, '\\');
	int n = p - text;
	grad_slist_append(slist, text, n);
	len -= n + 1;
	if (base == 16)
		len--;
	grad_slist_grow_backslash_num(slist, p, NULL, len, base);
}


